name: Flutter Build AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Configure Android Project
        run: |
          flutter create . --force --project-name=zikirmatik
          cd android
          echo "org.gradle.jvmargs=-Xmx1536m" > gradle.properties

      - name: Build AAB
        run: flutter build appbundle --release
